### ISSUE TITLE
[DB] 일정 기간이 지난 알람 데이터를 삭제해주기 위한 Event Scheduler 설정

### ISSUE THREAD

**Issue by jisu3817** [wooahan-agile/dongurami-server#410]
## 목적
> event 처리를 통해 정기적인 간격으로 일정 기간이 지난 알람 데이터를 삭제.

이벤트는 한 번 또는 정기적인 간격으로 나중 단계에서 실행될 SQL문을 포함하는 명명된 데이터베이스 개체이다.
Windows 작업 스케줄러나 Unix cron 작업과 비슷하다고 생각하면 된다.
필자는 정기적인 간격으로 DB 데이터를 삭제해주기 위해서 event scheduler를 사용했는데 이것 외에 Linux crontab과 같은 것을 활용할 수도 있다. 

</br>
</br>

- Event_Scheduler를 사용하기 위해 해당 기능이 ON으로 되어있는지 확인
```sql
SHOW GLOBAL VARIABLES WHERE VARIABLE_NAME = 'event_scheduler';
```
</br>
</br>

- 이벤트 생성
schedule은 DB에 종속되어 있어 해당 DB가 선택된 상태에서 생성해야 한다.
사용자가 읽거나 삭제 처리를 한 알람 데이터에 대해서 30일 보존 후 삭제하도록 이벤트 처리를 해주었다.
```sql
SHOW VARIABLES WHERE VARIABLE_NAME = 'event_scheduler'; -- event_scheduler = ON으로 되어있는지 확인.

CREATE EVENT IF NOT EXISTS noti_event_daily
ON SCHEDULE EVERY 1 DAY -- 매일 새벽 5시에 이벤트가 실행되도록 설정.
STARTS '2021-01-01 05:00:00' -- 여기서 지정된 날짜는 임의로 설정한 과거 기준 날짜임.
ON COMPLETION PRESERVE -- 이벤트가 실행되어도 삭제하지 않을 것임.
ENABLE 
COMMENT 'Delete alarm data after 30 days'
DO
DELETE notifications WHERE DATE(in_date) = DATE(subdate(now(), INTERVAL 30 DAY)) AND reading_flag = 1;

```

</br>
</br>

- schedule 확인
```sql
SHOW EVENTS; -- 현재 선택된 DB에 등록된 SChedule 조회.
or
SELECT * FROM information_schema.EVENTS; -- 모든 DB에 등록된 설정 조회.
```

</br>
</br>

- schedule 삭제 
```sql
DROP EVENT 이벤트명;
```

</br>
</br>

## 참고 자료
- https://mariadb.com/kb/en/events/

**Comment by ohchanghoon** [comment]
좋네요
